import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Meristem Securities Limited",
  description: "Generated by create next app",
};

const roobert = localFont({
  src: [
    {
      path: "./fonts/RoobertTRIAL-Regular-BF67243fd53fdf2.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/RoobertTRIAL-Medium-BF67243fd53e059.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/RoobertTRIAL-Bold-BF67243fd540abb.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/RoobertTRIAL-Light-BF67243fd502239.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/RoobertTRIAL-SemiBold-BF67243fd54213d.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/RoobertTRIAL-Heavy-BF67243fd53e164.otf",
      weight: "800",
      style: "normal",
    },
  ],
  // variable: "--font-roobert",
  // display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roobert.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
